version: "3.4"
name: retrobyte
services:
  mysql:
    image: mysql:8.0.42-oracle
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - network1
  app:
    image: retrobyte
    container_name: retrobytecon
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - network1
volumes:
  db:
networks:
  network1:
    driver: bridge